<?php
/** @var MageAustralia_Stripe_Block_Payment_Info_Base $this */
$status = $this->getPaymentStatus();
$piId = $this->getPaymentIntentId();
$checkoutType = $this->getCheckoutType();
?>
<div class="stripe-payment-info">
    <p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
    <table class="form-list">
        <?php if ($checkoutType): ?>
        <tr>
            <td class="label"><?php echo $this->escapeHtml($this->__('Checkout Type')) ?></td>
            <td class="value"><?php echo $this->escapeHtml(ucfirst($checkoutType)) ?></td>
        </tr>
        <?php endif; ?>
        <?php if ($piId): ?>
        <tr>
            <td class="label"><?php echo $this->escapeHtml($this->__('Payment Intent')) ?></td>
            <td class="value"><?php echo $this->escapeHtml($piId) ?></td>
        </tr>
        <?php endif; ?>
        <?php if ($status): ?>
        <tr>
            <td class="label"><?php echo $this->escapeHtml($this->__('Payment Status')) ?></td>
            <td class="value"><?php echo $this->escapeHtml(ucfirst($status)) ?></td>
        </tr>
        <?php endif; ?>
    </table>
</div>
